-- Seed equipment items
INSERT INTO equipmentitem (category, name, description, required) VALUES
('Tas & Carrier', 'Carrier 60-80L', 'Untuk membawa semua perlengkapan', true),
('Tas & Carrier', 'Daypack 20-30L', 'Untuk summit attack', true),
('Tas & Carrier', 'Dry Bag', 'Melindungi barang dari air', false),
('Tidur & Shelter', 'Tenda (Double Layer)', 'Tahan angin dan hujan', true),
('Tidur & Shelter', 'Sleeping Bag (-10°C to -15°C)', 'Sesuaikan suhu gunung', true),
('Tidur & Shelter', 'Sleeping Pad/Matras', 'Isolasi dari dingin tanah', true),
('Pakaian', 'Base Layer (Dry-fit)', 'Menyerap keringat', true),
('Pakaian', 'Mid Layer (Fleece)', 'Menjaga suhu tubuh', true),
('Pakaian', 'Outer Layer (Jaket Waterproof)', 'Tahan angin & hujan', true),
('Pakaian', 'Celana Outdoor', 'Cepat kering & nyaman', true),
('Pakaian', 'Sarung Tangan', 'Melindungi dari dingin', true),
('Pakaian', 'Kupluk/Topi', 'Menjaga kepala tetap hangat', true),
('Kaki', 'Sepatu Gunung (Mid/High Cut)', 'Ankle support & waterproof', true),
('Kaki', 'Gaiters', 'Melindungi dari kerikil & salju', false),
('Kaki', 'Sandal Gunung', 'Untuk di camp', false),
('Penerangan & Navigasi', 'Headlamp + Baterai Cadangan', 'Penerangan hands-free', true),
('Penerangan & Navigasi', 'GPS/Compass', 'Navigasi darurat', true),
('Makanan & Minum', 'Kompor Portable + Gas', 'Memasak di camp', true),
('Makanan & Minum', 'Nesting/Cookset', 'Peralatan memasak', true),
('Makanan & Minum', 'Water Bottle/Hydration Bladder', 'Minimal 2L kapasitas', true),
('Makanan & Minum', 'Water Purification Tablets', 'Sterilisasi air', false),
('Makanan & Minum', 'Makanan Instan/Energi', 'Mie, coklat, kacang, dll', true),
('Kesehatan & Keselamatan', 'First Aid Kit (P3K)', 'Obat-obatan dasar', true),
('Kesehatan & Keselamatan', 'Sunscreen & Lip Balm', 'Proteksi UV', true),
('Kesehatan & Keselamatan', 'Obat Pribadi', 'Sesuai kondisi kesehatan', true),
('Kesehatan & Keselamatan', 'Survival Blanket', 'Darurat hipotermia', false),
('Peralatan Tambahan', 'Trekking Pole', 'Mengurangi beban kaki', false),
('Peralatan Tambahan', 'Rain Cover/Cover Bag', 'Pelindung hujan untuk carrier', true),
('Peralatan Tambahan', 'Trash Bag', 'Prinsip Leave No Trace', true),
('Peralatan Tambahan', 'Power Bank', 'Cadangan daya', true),
('Peralatan Tambahan', 'Kamera/Action Cam', 'Dokumentasi', false);
